### PR TITLE
fix: split paths with semicolon

### PR DESCRIPTION
**Pull request by Aslemammad**
This was discussed in #140 for better platform compatibility.

### CODE REVIEW

**Comment by guybedford** [comment]
The original motivation for this was when dealing with windows paths like `C:\\path:C:\\another-path` being joined on a `:`. But since we are renormalizing the output now to use backtracking instead, I think this may not be as necessary?

**Comment by Aslemammad** [comment]
I see, that's reasonable! It's up to you at the end.

**Comment by guybedford** [comment]
Yeah it's just a breaking change like that other change, so would affect downstream at this point. We could certainly consider it for a major though.

**Comment by Aslemammad** [comment]
Let's close this then.

**Comment by guybedford** [comment]
Sure, and thanks for picking this question up from the discussion! If there are any other issues or extensions you're interested in working on always happy to discuss.

**Comment by Aslemammad** [comment]
Sure, I'd like to see chomp in a great stage that it deserves!

**Pull request closed without merging**
